# Generated by Django 5.0.7 on 2025-04-24 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ رویداد')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='تعطیل')),
                ('solar_day', models.IntegerField(blank=True, null=True, verbose_name='روز شمسی')),
                ('solar_month', models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی')),
                ('solar_year', models.IntegerField(blank=True, null=True, verbose_name='سال شمسی')),
                ('solar_day_week', models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته شمسی')),
                ('moon_day', models.IntegerField(blank=True, null=True, verbose_name='روز قمری')),
                ('moon_month', models.IntegerField(blank=True, null=True, verbose_name='ماه قمری')),
                ('moon_year', models.IntegerField(blank=True, null=True, verbose_name='سال قمری')),
                ('moon_day_week', models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته قمری')),
                ('gregorian_day', models.IntegerField(blank=True, null=True, verbose_name='روز میلادی')),
                ('gregorian_month', models.IntegerField(default=0, verbose_name='ماه میلادی')),
                ('gregorian_year', models.IntegerField(default=0, verbose_name='سال میلادی')),
                ('gregorian_day_week', models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته میلادی')),
                ('events', models.JSONField(blank=True, default=dict, null=True, verbose_name='رویدادها')),
            ],
            options={
                'verbose_name': 'رویداد تقویمی',
                'verbose_name_plural': 'رویدادهای تقویمی',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('temperature', models.FloatField(verbose_name='دما')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('temp_min', models.FloatField(blank=True, null=True, verbose_name='حداقل دما')),
                ('temp_max', models.FloatField(blank=True, null=True, verbose_name='حداکثر دما')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='رطوبت')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='فشار هوا')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='سرعت باد')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون')),
                ('weather_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات آب و هوا')),
                ('weather_icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون آب و هوا')),
                ('request_date_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
            ],
            options={
                'verbose_name': 'آب و هوا',
                'verbose_name_plural': 'اطلاعات آب و هوا',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('type_of_class', models.CharField(max_length=50, verbose_name='نوع کلاس')),
                ('departure_datetime', models.DateTimeField(verbose_name='تاریخ و زمان حرکت')),
                ('request_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درخواست')),
                ('bus_company', models.CharField(max_length=100, verbose_name='شرکت اتوبوسرانی')),
                ('bus_type', models.CharField(max_length=50, verbose_name='نوع اتوبوس')),
                ('amenities', models.JSONField(blank=True, default=list, null=True, verbose_name='امکانات')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.calendarevent', verbose_name='رویداد تقویمی')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا')),
            ],
            options={
                'verbose_name': 'اتوبوس',
                'verbose_name_plural': 'اتوبوس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('type_of_class', models.CharField(max_length=50, verbose_name='نوع کلاس')),
                ('departure_datetime', models.DateTimeField(verbose_name='تاریخ و زمان حرکت')),
                ('request_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درخواست')),
                ('flight_number', models.CharField(max_length=20, verbose_name='شماره پرواز')),
                ('airline', models.CharField(max_length=100, verbose_name='شرکت هواپیمایی')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان پرواز')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.calendarevent', verbose_name='رویداد تقویمی')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پروازها',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('type_of_class', models.CharField(max_length=50, verbose_name='نوع کلاس')),
                ('departure_datetime', models.DateTimeField(verbose_name='تاریخ و زمان حرکت')),
                ('request_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درخواست')),
                ('train_number', models.CharField(max_length=20, verbose_name='شماره قطار')),
                ('train_type', models.CharField(max_length=50, verbose_name='نوع قطار')),
                ('wagon_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد واگن')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.calendarevent', verbose_name='رویداد تقویمی')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا')),
            ],
            options={
                'verbose_name': 'قطار',
                'verbose_name_plural': 'قطارها',
            },
        ),
        migrations.CreateModel(
            name='CrawlerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler_type', models.CharField(choices=[('flight', 'پرواز'), ('train', 'قطار'), ('bus', 'اتوبوس')], max_length=10, verbose_name='نوع کراولر')),
                ('last_run', models.DateTimeField(auto_now_add=True, verbose_name='آخرین اجرا')),
                ('next_run', models.DateTimeField(verbose_name='اجرای بعدی')),
                ('status', models.CharField(choices=[('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'خطا'), ('pending', 'در انتظار')], max_length=20, verbose_name='وضعیت')),
                ('items_crawled', models.IntegerField(default=0, verbose_name='تعداد آیتم\u200cهای جمع\u200cآوری شده')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیغام خطا')),
                ('days_ahead', models.IntegerField(default=10, verbose_name='تعداد روزهای آینده')),
                ('bus_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.bus', verbose_name='اطلاعات اتوبوس')),
                ('flight_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight', verbose_name='اطلاعات پرواز')),
                ('train_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.train', verbose_name='اطلاعات قطار')),
            ],
            options={
                'verbose_name': 'وضعیت کراولر',
                'verbose_name_plural': 'وضعیت کراولرها',
                'ordering': ['-last_run'],
            },
        ),
    ]
