# Generated by Django 5.0.7 on 2025-05-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
    ]
