# Generated by Django 5.0.7 on 2025-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'آب و هوا', 'verbose_name_plural': 'اطلاعات آب و هوا'},
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='رطوبت'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='فشار هوا'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='request_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر دما'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(blank=True, null=True, verbose_name='حداقل دما'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(verbose_name='دما'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات آب و هوا'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون آب و هوا'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='سرعت باد'),
        ),
    ]
