# Generated by Django 5.0.7 on 2025-05-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_weather_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='weather_description',
            new_name='description',
        ),
    ]
