# Generated by Django 5.0.7 on 2025-04-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_weather_weather_description'),
    ]

    operations = [
    ]
