# Generated by Django 5.0.7 on 2025-05-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_weather_description_weather_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-request_date_time'], 'verbose_name': 'آب و هوا', 'verbose_name_plural': 'اطلاعات آب و هوا'},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_icon',
        ),
        migrations.AlterField(
            model_name='bus',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weather', to='flights.weather', verbose_name='آب و هوا'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weather', to='flights.weather', verbose_name='آب و هوا'),
        ),
        migrations.AlterField(
            model_name='train',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weather', to='flights.weather', verbose_name='آب و هوا'),
        ),
    ]
