# Generated by Django 5.0.7 on 2025-05-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_weather_options_remove_weather_weather_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'آب و هوا', 'verbose_name_plural': 'اطلاعات آب و هوا'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا'),
        ),
        migrations.AlterField(
            model_name='train',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.weather', verbose_name='آب و هوا'),
        ),
    ]
