# Generated by Django 5.0.7 on 2025-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_weather_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات آب و هوا'),
        ),
    ]
