# Generated by Django 5.0.7 on 2025-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_weather_description_weather_weather_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='humidity',
        ),
        
        migrations.RemoveField(
            model_name='weather',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather_icon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
    ]
