# Generated by Django 5.0.7 on 2025-05-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_weather_options_alter_bus_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='solar_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز شمسی'),
        ),
        migrations.AddField(
            model_name='bus',
            name='solar_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی'),
        ),
        migrations.AddField(
            model_name='bus',
            name='solar_weekday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته شمسی'),
        ),
        migrations.AddField(
            model_name='bus',
            name='solar_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال شمسی'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='solar_weekday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته شمسی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='solar_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز شمسی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='solar_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='solar_weekday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته شمسی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='solar_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال شمسی'),
        ),
        migrations.AddField(
            model_name='train',
            name='solar_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز شمسی'),
        ),
        migrations.AddField(
            model_name='train',
            name='solar_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی'),
        ),
        migrations.AddField(
            model_name='train',
            name='solar_weekday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='روز هفته شمسی'),
        ),
        migrations.AddField(
            model_name='train',
            name='solar_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال شمسی'),
        ),
    ]
