# Generated by Django 5.0.7 on 2025-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_weather_description_remove_weather_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='رطوبت'),
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='فشار هوا'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر دما'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(blank=True, null=True, verbose_name='حداقل دما'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='دما'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات آب و هوا'),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='آیکون آب و هوا'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='سرعت باد'),
        ),
    ]
